[package]
name = "typstyle-embedded"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["QuadnucYard", "Wenzhuo Liu"]
description = "Embedded Typstyle for Typst"
homepage = "https://typstyle-rs.github.io/typstyle"
repository = "https://github.com/typstyle-rs/typstyle"
keywords = ["typstyle", "formatter"]
compiler = "0.13.0"
